// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/thumbnails/*": {
    params: {
      "*": string;
    };
  };
  "/onboarding": {
    params: {};
  };
  "/media/*": {
    params: {
      "*": string;
    };
  };
  "/auth": {
    params: {};
  };
  "/auth/forgot-password": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/app": {
    params: {};
  };
  "/app/videos/:id": {
    params: {
      "id": string;
    };
  };
  "/app/settings": {
    params: {};
  };
  "/app/prompt": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/thumbnails/*" | "/onboarding" | "/media/*" | "/auth" | "/auth/forgot-password" | "/auth/register" | "/auth/login" | "/app" | "/app/videos/:id" | "/app/settings" | "/app/prompt";
  };
  "routes/thumbnails.$.tsx": {
    id: "routes/thumbnails.$";
    page: "/thumbnails/*";
  };
  "routes/onboarding.tsx": {
    id: "routes/onboarding";
    page: "/onboarding";
  };
  "routes/media.$.tsx": {
    id: "routes/media.$";
    page: "/media/*";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth" | "/auth/forgot-password" | "/auth/register" | "/auth/login";
  };
  "routes/auth.forgot-password.tsx": {
    id: "routes/auth.forgot-password";
    page: "/auth/forgot-password";
  };
  "routes/auth.register.tsx": {
    id: "routes/auth.register";
    page: "/auth/register";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/videos/:id" | "/app/settings" | "/app/prompt";
  };
  "routes/app.videos.$id.tsx": {
    id: "routes/app.videos.$id";
    page: "/app/videos/:id";
  };
  "routes/app.settings.tsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.prompt.tsx": {
    id: "routes/app.prompt";
    page: "/app/prompt";
  };
};