name: ðŸ› Bug Report
description: Create a report to help us improve Edit Mind
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Where did this bug occur?
      options:
        - Desktop App (Windows)
        - Desktop App (macOS)
        - Desktop App (Linux)
        - Web App (Docker / Self-Hosted)
        - Background Jobs Service
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Edit Mind Version
      description: Which version are you using? (e.g., v0.1.1)
      placeholder: v0.1.1
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
      placeholder: When I click on "Index Video", the app crashes...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to 'Settings'
        2. Click on 'Add Folder'
        3. Select a folder with .mkv files
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs & Screenshots
      description: |
        Please copy and paste any relevant logs.
        - **Desktop:** View -> Toggle Developer Tools -> Console
        - **Web/Docker:** `docker compose logs -f`
      render: shell
