name: 🚀 Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please check existing issues to avoid duplicates.

  - type: dropdown
    id: platform
    attributes:
      label: Target Platform
      description: Which part of Edit Mind would this feature improve?
      options:
        - All Platforms (Core Experience)
        - Desktop App Specific
        - Web App / Studio Specific
        - AI / Analysis Plugins
        - Developer Experience / API
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when I have to manually tag 50 videos...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like a "Batch Auto-Tag" button that uses the AI to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: dropdown
    id: impact
    attributes:
      label: Impact / Priority
      description: How much value would this add to your workflow?
      options:
        - Critical (I cannot use the software without this)
        - High (Would significantly improve my daily workflow)
        - Medium (Nice to have)
        - Low (Minor polish)
    validations:
      required: true
