FROM node:22.20.0

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && corepack prepare pnpm@8.6.9 --activate

WORKDIR /app

# Copy package files
COPY pnpm-workspace.yaml ./
COPY pnpm-lock.yaml ./
COPY package.json ./
COPY prisma.config.ts ./
COPY apps/web/ ./apps/web
COPY apps/background-jobs/package.json ./apps/background-jobs/
COPY packages/shared/ ./packages/shared
COPY packages/prisma/ ./packages/prisma

# Install dependencies
RUN --mount=type=cache,id=pnpm,target=/root/.pnpm-store pnpm install --frozen-lockfile
RUN pnpm rebuild @tailwindcss/oxide
RUN pnpm rebuild rollup


# Copy necessary config files
COPY tsconfig.json ./
COPY apps/web/vite.config.ts ./apps/web/vite.config.ts

EXPOSE 3745

CMD ["sh", "-c", "pnpm prisma migrate deploy && pnpm prisma generate && pnpm prisma db seed &&  pnpm prisma generate  && pnpm --filter web start --port 3745 --host"]
