FROM python:3.11-slim

WORKDIR /app

COPY python/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./python .

EXPOSE 8765

CMD ["python", "analysis_service.py", "--port", "8765"]
