ARG NODE_VERSION=22.20.0
ARG PNPM_VERSION=10.20.0

FROM node:${NODE_VERSION}-slim AS base

ARG PNPM_VERSION

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && corepack prepare pnpm@${PNPM_VERSION} --activate

WORKDIR /app

FROM base AS dependencies

RUN apt-get update && apt-get install -y --no-install-recommends \
    openssl \
    ca-certificates \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY pnpm-workspace.yaml pnpm-lock.yaml package.json prisma.config.ts ./
COPY apps/web/package.json ./apps/web/
COPY apps/background-jobs/package.json ./apps/background-jobs/
COPY packages/shared/package.json ./packages/shared/
COPY packages/prisma ./packages/prisma/

RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --frozen-lockfile

FROM dependencies AS builder

COPY apps ./apps
COPY packages ./packages
COPY tsconfig.json ./

RUN pnpm --filter prisma generate

RUN pnpm rebuild @tailwindcss/oxide rollup sharp

RUN pnpm --filter web install --frozen-lockfile

RUN pnpm --filter web build

FROM builder AS development

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    vim \
    && rm -rf /var/lib/apt/lists/*

ENV NODE_ENV=development


WORKDIR /app/

EXPOSE 3745

CMD ["sh", "-c", "pnpm prisma migrate deploy && pnpm prisma generate  && pnpm dev --host 0.0.0.0 --port 3745 --filter web"]