export const video = [
  {
    id: '',
    source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    scenes: [
      {
        id: '1',
        startTime: 0,
        endTime: 45,
        objects: ['grass', 'trees', 'butterflies'],
        faces: ['Bunny'],
        transcription: 'The forest awakens to a calm morning breeze.',
        description: 'A wide shot of a peaceful meadow filled with tall grass and butterflies flying around.',
        shot_type: 'wide',
        thumbnailUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&q=80&w=1335',
        emotions: [{ name: 'Bunny', emotion: 'peaceful' }],
        source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        category: 'nature',
        aspect_ratio: '16:9',
        camera: 'RED Komodo 6K',
        createdAt: '2025-11-04T10:00:00.000Z',
        dominantColorHex: '#7BB661',
        dominantColorName: 'forest green',
        location: 'Sunny meadow',
        duration: 45,
        detectedText: [],
      },
      {
        id: '2',
        startTime: 45,
        endTime: 120,
        objects: ['Bunny', 'rocks', 'birds'],
        faces: ['Bunny'],
        transcription: 'Meet our hero, the curious bunny.',
        description: 'Close-up of the bunny sniffing around rocks while birds chirp nearby.',
        shot_type: 'close-up',
        thumbnailUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&q=80&w=1335',
        emotions: [{ name: 'Bunny', emotion: 'curious' }],
        source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        category: 'introduction',
        aspect_ratio: '16:9',
        camera: 'Sony FX3',
        createdAt: '2025-11-04T10:02:00.000Z',
        dominantColorHex: '#E6C79C',
        dominantColorName: 'sand beige',
        location: 'Rocky clearing',
        duration: 75,
        detectedText: [],
      },
      {
        id: '3',
        startTime: 120,
        endTime: 180,
        objects: ['butterfly', 'Bunny'],
        faces: ['Bunny'],
        transcription: 'Oh! What a beautiful butterfly!',
        description: 'The bunny joyfully watches a butterfly flutter by in slow motion.',
        shot_type: 'medium',
        thumbnailUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1335',
        emotions: [{ name: 'Bunny', emotion: 'joyful' }],
        source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        category: 'interaction',
        aspect_ratio: '16:9',
        camera: 'Blackmagic URSA Mini Pro',
        createdAt: '2025-11-04T10:05:00.000Z',
        dominantColorHex: '#9BD3E0',
        dominantColorName: 'sky blue',
        location: 'Forest glade',
        duration: 60,
        detectedText: [],
      },
      {
        id: '4',
        startTime: 180,
        endTime: 250,
        objects: ['squirrel', 'bird', 'Bunny'],
        faces: ['Bunny', 'Squirrel', 'Bird'],
        transcription: 'Troublemakers arrive, teasing the bunny.',
        description: 'A group of mischievous animals interrupt the bunnys peace.',
        shot_type: 'medium',
        thumbnailUrl: 'https://images.unsplash.com/photo-1481349518771-20055b2a7b24?auto=format&fit=crop&q=80&w=1335',
        emotions: [
          { name: 'Bunny', emotion: 'annoyed' },
          { name: 'Squirrel', emotion: 'playful' },
        ],
        source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        category: 'conflict',
        aspect_ratio: '16:9',
        camera: 'Canon C70',
        createdAt: '2025-11-04T10:08:00.000Z',
        dominantColorHex: '#C6A76A',
        dominantColorName: 'golden brown',
        location: 'Forest edge',
        duration: 70,
        detectedText: [],
      },
      {
        id: '5',
        startTime: 250,
        endTime: 320,
        objects: ['Bunny', 'birds', 'rocks'],
        faces: ['Bunny'],
        transcription: 'The chase begins!',
        description: 'The bunny runs through the forest as the birds chase him playfully.',
        shot_type: 'tracking',
        thumbnailUrl: 'https://images.unsplash.com/photo-1494783367193-149034c05e8f?auto=format&fit=crop&q=80&w=1335',
        emotions: [{ name: 'Bunny', emotion: 'frightened' }],
        source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        category: 'chase',
        aspect_ratio: '16:9',
        camera: 'DJI Inspire 2',
        createdAt: '2025-11-04T10:11:00.000Z',
        dominantColorHex: '#708D81',
        dominantColorName: 'moss green',
        location: 'Woodland path',
        duration: 70,
        detectedText: ['CAUTION'],
      },
      {
        id: '6',
        startTime: 320,
        endTime: 400,
        objects: ['Bunny', 'stick', 'birds'],
        faces: ['Bunny'],
        transcription: 'No more running! Time to fight back!',
        description: 'The bunny turns around, ready to defend himself.',
        shot_type: 'close-up',
        thumbnailUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&q=80&w=1335',
        emotions: [{ name: 'Bunny', emotion: 'angry' }],
        source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        category: 'action',
        aspect_ratio: '16:9',
        camera: 'Sony FX6',
        createdAt: '2025-11-04T10:13:00.000Z',
        dominantColorHex: '#A45D5D',
        dominantColorName: 'brick red',
        location: 'Forest clearing',
        duration: 80,
        detectedText: [],
      },
      {
        id: '7',
        startTime: 400,
        endTime: 480,
        objects: ['trap', 'Bunny', 'birds'],
        faces: ['Bunny'],
        transcription: 'A trap is set for the troublemakers.',
        description: 'The bunny cleverly sets a trap under a tree branch.',
        shot_type: 'medium',
        thumbnailUrl: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&q=80&w=1335',
        emotions: [{ name: 'Bunny', emotion: 'focused' }],
        source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        category: 'strategy',
        aspect_ratio: '16:9',
        camera: 'Canon R5C',
        createdAt: '2025-11-04T10:15:00.000Z',
        dominantColorHex: '#8F9779',
        dominantColorName: 'sage green',
        location: 'Forest trap area',
        duration: 80,
        detectedText: [],
      },
      {
        id: '8',
        startTime: 480,
        endTime: 560,
        objects: ['Bunny', 'birds', 'trap'],
        faces: ['Bunny', 'Bird Leader'],
        transcription: 'Gotcha! Revenge is sweet.',
        description: 'The trap catches the troublemakers, and the bunny celebrates victory.',
        shot_type: 'wide',
        thumbnailUrl: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&q=80&w=1335',
        emotions: [
          { name: 'Bunny', emotion: 'triumphant' },
          { name: 'Bird Leader', emotion: 'shocked' },
        ],
        source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        category: 'resolution',
        aspect_ratio: '16:9',
        camera: 'RED Komodo 6K',
        createdAt: '2025-11-04T10:17:00.000Z',
        dominantColorHex: '#C0A080',
        dominantColorName: 'warm beige',
        location: 'Forest clearing',
        duration: 80,
        detectedText: [],
      },
      {
        id: '9',
        startTime: 560,
        endTime: 596,
        objects: ['Bunny', 'forest'],
        faces: ['Bunny'],
        transcription: 'And thats the end of our story.',
        description: 'The bunny rests peacefully as the credits roll over the sunset.',
        shot_type: 'wide',
        thumbnailUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&q=80&w=1335',
        emotions: [{ name: 'Bunny', emotion: 'content' }],
        source: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        category: 'ending',
        aspect_ratio: '16:9',
        camera: 'Sony FX3',
        createdAt: '2025-11-04T10:20:00.000Z',
        dominantColorHex: '#F4C27F',
        dominantColorName: 'sunset gold',
        location: 'Meadow sunset',
        duration: 36,
        detectedText: ['THE END'],
      },
    ],
  },
]

export const suggestions = [
  {
    text: 'Show me happy moments',
    icon: '😊',
    gradient: 'from-yellow-500/20 to-orange-500/20',
    border: 'border-yellow-200 dark:border-yellow-900/50',
    hover: 'hover:shadow-yellow-500/20',
  },
  {
    text: 'Find wildlife footage',
    icon: '🦁',
    gradient: 'from-green-500/20 to-emerald-500/20',
    border: 'border-green-200 dark:border-green-900/50',
    hover: 'hover:shadow-green-500/20',
  },
  {
    text: 'Action and adventure clips',
    icon: '⚡',
    gradient: 'from-blue-500/20 to-cyan-500/20',
    border: 'border-blue-200 dark:border-blue-900/50',
    hover: 'hover:shadow-blue-500/20',
  },
  {
    text: 'Peaceful nature scenes',
    icon: '🏔️',
    gradient: 'from-purple-500/20 to-pink-500/20',
    border: 'border-purple-200 dark:border-purple-900/50',
    hover: 'hover:shadow-purple-500/20',
  },
];
